### PR TITLE
optimization debian package manager tweaks

### PR DESCRIPTION
**Pull request by Rajpratik71**
By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages .

By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.

This results in smaller downloads and installation of packages .

Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .

Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

### CODE REVIEW

**Comment by Rajpratik71** [comment]
@kant @xudifsd requesting review

**Comment by Rajpratik71** [comment]
@YinYangOfDao requesting review

**Comment by YinYangOfDao** [comment]
looks good to me as well, but we are actively developing in dltsdev branch, not sure whether merge into master branch at this point, need to discuss with colleagues. thanks for the contribution~

**Comment by Rajpratik71** [comment]
> looks good to me as well, but we are actively developing in dltsdev branch, not sure whether merge into master branch at this point, need to discuss with colleagues. thanks for the contribution~

should i make PR to dltsdev branch

**Comment by xudifsd** [comment]
> > looks good to me as well, but we are actively developing in dltsdev branch, not sure whether merge into master branch at this point, need to discuss with colleagues. thanks for the contribution~
> 
> should i make PR to dltsdev branch

yes, please.

**Comment by Rajpratik71** [comment]
> > > looks good to me as well, but we are actively developing in dltsdev branch, not sure whether merge into master branch at this point, need to discuss with colleagues. thanks for the contribution~
> > 
> > 
> > should i make PR to dltsdev branch
> 
> yes, please.

created a new PR #905 to branch dltsdev as requested

**Comment by xudifsd** [comment]
merged into dltsdev, and close this one.

**Pull request closed without merging**
