### PR TITLE
Dashboard: add timeout field

### PR DESCRIPTION
**Pull request by Gerhut**
Merge priority column with the actual field before do the actual code, in order to fork to the timeout field.

image

### CODE REVIEW

**Comment by xudifsd** [comment]
Front end support for #1147

**Comment by xudifsd** [comment]
Is this finished or not? Do you support user input "1d" and convert to "86400" second? Also display this instead of in second.

**Comment by Anbang-Hu** [comment]
> Is this finished or not? Do you support user input "1d" and convert to "86400" second? Also display this instead of in second.

Let's use hours. We use GPU hours as the unit for GPU compute consumption by users.

**Comment by Gerhut** [comment]
Deployed to int

**Pull request merged**
