### PR TITLE
add entries to /etc/hosts

### PR DESCRIPTION
**Pull request by xudifsd**

### CODE REVIEW

**Comment by hongzhili** [comment]
Please deploy this change to RR1-2.

**Comment by hongzhili** [comment]
Please deploy this change to RR1-2. @xudifsd @Anbang-Hu

**Comment by xudifsd** [comment]
@Anbang-Hu should we cherry pick this to r1.4?

**Comment by xudifsd** [comment]
@hongzhili done deployment, tested with regular job, works as expected

**Pull request merged**
