### PR TITLE
Fix dashboard deployment

### PR DESCRIPTION
**Pull request by Gerhut**

### CODE REVIEW

**Comment by hongzhili** [comment]
May I get the context of this change? Is winbindserver a list now?

**Comment by Gerhut** [comment]
> May I get the context of this change? Is winbindserver a list now?

Yes, `winbind` field in config.yaml is always list, which should be a single string here

**Comment by Anbang-Hu** [comment]
Can we parameterize these two configs as well?
```
AddGroupLink
```

**Comment by Gerhut** [comment]
> Can we parameterize these two configs as well?
> 
> ```
> AddGroupLink
> WikiLink
> ```

It's restructured in `https://github.com/microsoft/DLWorkspace/pull/714`, will open in a new PR

**Pull request merged**
